<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>T13_Correlacion</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="custom.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">BIOL 3740</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Descripción.html">Home</a>
</li>
<li>
  <a href="schedule.html">Calendario</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Instalación y Introducción básica
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Instalar-R-RStudio.html">Instalar R y RStudio</a>
    </li>
    <li>
      <a href="Introducción_RMarkdown.html">RMarkdown</a>
    </li>
    <li>
      <a href="Codigos_basicos_en_R.html">Codigos Básicos en R</a>
    </li>
    <li>
      <a href="R_basico.html">R Básico #2</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Los Temas
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="T1_Intro.html">T1 Introducción a la Estadística</a>
    </li>
    <li>
      <a href="T1a_Poblacion_Muestra.html">T1a Población, Muestreo y Sesgo</a>
    </li>
    <li>
      <a href="T1b_Inferencias_hipotesis.html">T1b Inferencias y hipotesis</a>
    </li>
    <li>
      <a href="T2_Historia.html">T2 Historia breve de la estadística cuantitativa</a>
    </li>
    <li>
      <a href="T3_Medidas_tendencia_central.html">T3 Medidas de Tedencias Central</a>
    </li>
    <li>
      <a href="T4_Medidas_dispersión.html">T4 Medidas de Dispersión</a>
    </li>
    <li>
      <a href="T4a_Estadistica_descriptiva.html">T4a Estadística Descriptiva</a>
    </li>
    <li>
      <a href="T5_Graficos.html">T5 Explorando los datos con gráficos</a>
    </li>
    <li>
      <a href="T6_supuestos.html">T6 Los Supuestos de las pruebas parametricas</a>
    </li>
    <li>
      <a href="T7_Frecuencias.html">T7 Pruebas de Bondad de Ajuste</a>
    </li>
    <li>
      <a href="T8_Distribucion_Normal.html">T8 La Distribución Normal</a>
    </li>
    <li>
      <a href="T13_Correlacion_Covarianza.html">T13 Correlación y Covarianza</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Ejercicios
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Plataforma.html">Ejercico Plataforma de RStudio</a>
    </li>
    <li>
      <a href="RMarkdown.html">Ejercico Plataforma de RMarkdown</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Los Datos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Archivos_de_Datos.html">Archivos de Datos</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">T13_Correlacion</h1>

</div>


<p>Fecha de la ultima revisión</p>
<pre><code>## [1] &quot;2020-07-27&quot;</code></pre>
<div id="install-packages" class="section level2">
<h2>Install packages</h2>
<p>La correlaciones son métodos para evaluar la relación entre dos o más variables.</p>
<p>Ejemplos</p>
<ol style="list-style-type: decimal">
<li>La cantidad de colesterol, LDL (lipoproteínas de baja densidad) y HDL (lipoproteínas de alta densidad).</li>
<li>La concentración de vitamina C y la absorción de calcio.</li>
<li>La consumo de alcohol y la concentración de alcohol en la sangre.</li>
</ol>
<p>Los analísis se hacen comparando las variables continuas en pares. La covarianza es la medida de variabilidad conjunta entre dos variables.</p>
<p>Primero recordamos la formula para calcular la varianza de una variable</p>
<p><span class="math display">\[s^{ 2 }=\frac { \sum _{ i=1 }^{ n }{ (x_{ i }-\bar { x } ) } ^{ 2 } }{ n-1 }\]</span></p>
<p>Ahora la vamos a descomponer</p>
<p><span class="math display">\[s^{ 2 }=\frac { \sum _{ i=1 }^{ n }{ (x_{ i }-\bar{ x } ) } (x_{ i }-\bar { x } ) }{ n-1 }\]</span></p>
</div>
<div id="correlación-de-pearson" class="section level1">
<h1>Correlación de Pearson</h1>
<p>Esta la más común y conocida como el Coeficiente de correlación de Pearson. Nota ahora que tenemos dos variables <strong>x</strong> y <strong>y</strong>.</p>
<p>Podemos ver cual es la relación entre la edad de los estudiantes y cuantas veces fueron a Disney en Orlando, Florida. El objetivo es evaluar el covarianza entre una variable y otra.</p>
<table>
<thead>
<tr class="header">
<th>Personas</th>
<th>Maria</th>
<th>Juan</th>
<th>José</th>
<th>Carla</th>
<th>Luis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Edad (x)</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>13</td>
<td>15</td>
</tr>
<tr class="even">
<td>Veces a Disney (y)</td>
<td>5</td>
<td>4</td>
<td>4</td>
<td>6</td>
<td>8</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th>Personas</th>
<th>Edad (x)</th>
<th>x^2</th>
<th>Veces a Disney (y)</th>
<th>y^2</th>
<th>xy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>María</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>13</td>
<td>15</td>
</tr>
<tr class="even">
<td>Juan</td>
<td>9</td>
<td>4</td>
<td>4</td>
<td>6</td>
<td>8</td>
</tr>
<tr class="odd">
<td>José</td>
<td>10</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Carla</td>
<td>13</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Luis</td>
<td>15</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Sumas</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>La siguiente formula muestra el calculo para el coeficiente de Pearson <span class="math inline">\(\rho\)</span> que se dice <strong>rho</strong> que es el parámetro (el universo). Para significar el coeficiente de una muestra se usa la <strong>r</strong>.</p>
<p><span class="math display">\[r=\frac { cov(x,y) }{ { s }_{ x }{ s }_{ y } } =\frac { \sum { ({ x }_{ i }-\bar { x } _{ i })({ y }_{ i }-\bar { y } _{ i }) }  }{ n-1({ s }_{ x }{ s }_{ y }) }\]</span> Una otra manera de ver como se calcula el coeficiente es usar la siguiente formula.</p>
<p><span class="math display">\[r=\frac{\sum_{ }^{ }xy-\left(\frac{\sum_{ }^{ }x\sum_{ }^{ }y}{n}\right)}{\sqrt{\left(\sum_{ }^{ }x^2-\frac{\left(\sum_{ }^{ }x\right)^2}{n}\right)\left(\sum_{ }^{ }y^2-\frac{\left(\sum_{ }^{ }y\right)^2}{n}\right)}}\]</span></p>
<p>Creamos un conjunto de datos para demostrar como se calcula</p>
<pre class="r"><code>Edad&lt;-c(8,9,10,13,15)
Disney&lt;-c(5,4,4,6,8)
dfDisney&lt;-data.frame(Edad, Disney) # unir las listas en un data frame
dfDisney$Edad2=dfDisney$Edad^2
dfDisney$Disney2=dfDisney$Disney^2
dfDisney$Edad_por_Disney=dfDisney$Edad*dfDisney$Disney
dfDisney</code></pre>
<pre><code>##   Edad Disney Edad2 Disney2 Edad_por_Disney
## 1    8      5    64      25              40
## 2    9      4    81      16              36
## 3   10      4   100      16              40
## 4   13      6   169      36              78
## 5   15      8   225      64             120</code></pre>
<p>Lo que necesitamos ahora es calcular cada una de las variables</p>
<pre class="r"><code>library(knitr)
library(kableExtra)
df &lt;- data.frame(Formulas = c(&quot;$$\\sum x $$&quot;,&quot;$$\\sum y$$&quot;, &quot;$$\\sum x^2$$&quot;, &quot;$$\\sum y^2$$&quot;, &quot;$$\\sum xy$$&quot;),
                 Sumas = c(55, 27, 639,157, 314))

kable(df, escape=FALSE)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
Formulas
</th>
<th style="text-align:right;">
Sumas
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math display">\[\sum x \]</span>
</td>
<td style="text-align:right;">
55
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math display">\[\sum y\]</span>
</td>
<td style="text-align:right;">
27
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math display">\[\sum x^2\]</span>
</td>
<td style="text-align:right;">
639
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math display">\[\sum y^2\]</span>
</td>
<td style="text-align:right;">
157
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math display">\[\sum xy\]</span>
</td>
<td style="text-align:right;">
314
</td>
</tr>
</tbody>
</table>
<p>Ahora sustituir los valores en la ecuación para calcular el coeficiente de Pearson.</p>
<p><span class="math display">\[r=\frac{314-\left(\frac{55\cdot27}{5}\right)}{\sqrt{\left(639-\frac{\left(55\right)^2}{5}\right)\left(157-\frac{\left(27\right)^2}{5}\right)}}=0.871\]</span> La función para hacer todos estos calculo es <strong>cor</strong>. Con una correlación de 0.87, esto significa que hay buena correlación positiva entre la edad y la cantidad de veces que han ido a Disney.</p>
<pre class="r"><code>cor(Edad, Disney)</code></pre>
<pre><code>## [1] 0.8711651</code></pre>
<p>Un gráfico de Correlación sencilla. Miran que parece haber un patrón de cuando aumenta una variable aumenta la otra.</p>
<pre class="r"><code>scatter&lt;-ggplot(dfDisney, aes(x=Edad, y=Disney))
scatter + geom_point(colour=&quot;purple&quot;)+
  geom_hline(aes(yintercept=mean(Disney)))+ # las lineas representa el promedio de la variable en *y* los valores
  geom_vline(aes(xintercept=mean(Edad))) # las lineas representa el promedio de la variable en *x* los valores</code></pre>
<p><img src="T13_Correlacion_files/figure-html/graph%20correlations-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
<div id="el-rango-del-coeficiente-pearson" class="section level1">
<h1>El rango del coeficiente Pearson</h1>
<p>El coeficiente de correlación varía de −1 a 1. El valor de 1 implica que la relación entre X e Y es perfecta positiva, en otra palabra la <strong>x</strong> predice exactamente el valor de <strong>y</strong>. Un valor de -1 implica que los datos predicen una relación negativa perfecta entre la <strong>x</strong> y <strong>y</strong>. Cuando el valor de 0 o cerca esto implica que no existe una correlación lineal entre las variables.</p>
<p>Los supuestos del modelo</p>
<ol style="list-style-type: decimal">
<li>Uno de los supuestos de la prueba de análisis de Pearson, es que las dos variables tenga una distribución normal, <strong>Nornal bivariada</strong>.</li>
<li>Las variables tienen que tener una correlación lineal (no por cuadrática o logarítmica).</li>
</ol>
<p>Para visualizar una distribución vea lo siguiente. Nota que ls dos variables tienen una distribución normal.</p>
<p>Este gráfico proviene del siguiente website <a href="http://lertap5.com/RMCS2017/HTML/bivariate-normal.html" class="uri">http://lertap5.com/RMCS2017/HTML/bivariate-normal.html</a></p>
<p><img src="Graficos/Bivariate_normal.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Dealing with missing values use the following function use = “pairwise.complete.obs”.</p>
<div id="kendall-correlation" class="section level2">
<h2>Kendall Correlation</h2>
<p>In statistics, the Kendall rank correlation coefficient, commonly referred to as Kendall’s tau coefficient (after the Greek letter τ), is a statistic used to measure the ordinal association between two measured quantities. A tau test is a non-parametric hypothesis test for statistical dependence based on the tau coefficient.</p>
<p>It is a measure of rank correlation: the similarity of the orderings of the data when ranked by each of the quantities. It is named after Maurice Kendall, who developed it in 1938,[1] though Gustav Fechner had proposed a similar measure in the context of time series in 1897.</p>
<p>Intuitively, the Kendall correlation between two variables will be high when observations have a similar (or identical for a correlation of 1) rank (i.e. relative position label of the observations within the variable: 1st, 2nd, 3rd, etc.) between the two variables, and low when observations have a dissimilar (or fully different for a correlation of -1) rank between the two variables.</p>
</div>
<div id="spearman-correlation" class="section level2">
<h2>Spearman Correlation</h2>
<p>In statistics, Spearman’s rank correlation coefficient or Spearman’s rho, named after Charles Spearman and often denoted by the Greek letter ρ(rho), is a nonparametric measure of rank correlation (statistical dependence between the rankings of two variables). It assesses how well the relationship between two variables can be described using a monotonic function.</p>
<p>The Spearman correlation between two variables is equal to the Pearson correlation between the rank values of those two variables; while Pearson’s correlation assesses linear relationships, Spearman’s correlation assesses monotonic relationships (whether linear or not). If there are no repeated data values, a perfect Spearman correlation of +1 or −1 occurs when each of the variables is a perfect monotone function of the other.</p>
<p>Intuitively, the Spearman correlation between two variables will be high when observations have a similar (or identical for a correlation of 1) rank (i.e. relative position label of the observations within the variable: 1st, 2nd, 3rd, etc.) between the two variables, and low when observations have a dissimilar (or fully opposed for a correlation of −1) rank between the two variables.</p>
</div>
</div>
<div id="the-strenght-of-the-correlation-is-based-on-the-absolute-number" class="section level1">
<h1>THE STRENGHT of the correlation is based on the ABSOLUTE NUMBER</h1>
<p>Using use = “everything”, Si Hay 1 “NA” en la los datos, elimina la variable completa use = “complete.obs”, Si hay 1 “NA”, Elimina el individuo que tiene NA para todas los calculos use = “pairwise.complete.obs”, Si hay un “NA”, Elimina el individuo solamente si el par evaluado tiene un “NA”.</p>
<p>Whereas with use=“pairwise.complete.obs” , the cases with missing values are only removed during the calculation of each pairwise correlation. Thus we see that the correlation between x and z is the same in both matrices but the correlation between y and both x and z depends on the use method (with dramatic effect).</p>
<pre class="r"><code>#-----Dealing with misisng cases

adverts&lt;-c(15,14,14,6,2)
comprasNA&lt;-c(8,9,10,NA,15)
age&lt;-c(5, 12, 16, 9, 14)
advertNA&lt;-data.frame(adverts, comprasNA, age)

head(advertNA)</code></pre>
<pre><code>##   adverts comprasNA age
## 1      15         8   5
## 2      14         9  12
## 3      14        10  16
## 4       6        NA   9
## 5       2        15  14</code></pre>
<pre class="r"><code>cor(advertNA, use = &quot;everything&quot;,  method = &quot;pearson&quot;)</code></pre>
<pre><code>##              adverts comprasNA        age
## adverts    1.0000000        NA -0.2194619
## comprasNA         NA         1         NA
## age       -0.2194619        NA  1.0000000</code></pre>
<pre class="r"><code>cor(advertNA, use = &quot;complete.obs&quot;,  method = &quot;pearson&quot;)</code></pre>
<pre><code>##              adverts  comprasNA        age
## adverts    1.0000000 -0.9794293 -0.3799803
## comprasNA -0.9794293  1.0000000  0.5486947
## age       -0.3799803  0.5486947  1.0000000</code></pre>
<pre class="r"><code>cor(advertNA, use = &quot;pairwise.complete.obs&quot;,  method = &quot;pearson&quot;) # Comunente usado.  </code></pre>
<pre><code>##              adverts  comprasNA        age
## adverts    1.0000000 -0.9794293 -0.2194619
## comprasNA -0.9794293  1.0000000  0.5486947
## age       -0.2194619  0.5486947  1.0000000</code></pre>
<pre class="r"><code>cor(advertNA, use = &quot;pairwise.complete.obs&quot;,  method = &quot;kendall&quot;)   </code></pre>
<pre><code>##              adverts  comprasNA        age
## adverts    1.0000000 -0.9128709 -0.3162278
## comprasNA -0.9128709  1.0000000  0.6666667
## age       -0.3162278  0.6666667  1.0000000</code></pre>
<pre class="r"><code>cor(advertNA, use = &quot;pairwise.complete.obs&quot;,  method = &quot;spearman&quot;) # n= 30 or more</code></pre>
<pre><code>##              adverts  comprasNA        age
## adverts    1.0000000 -0.9486833 -0.4103913
## comprasNA -0.9486833  1.0000000  0.8000000
## age       -0.4103913  0.8000000  1.0000000</code></pre>
<p>Anxiety data</p>
<pre class="r"><code>library(readr)
Exam_Anxiety &lt;- read_csv(&quot;~/Google Drive/Biometry/Biometria 2015/Biometria_2015_RStudio/Data files/Exam_Anxiety.csv&quot;)
examData=Exam_Anxiety
head(examData)</code></pre>
<pre><code>## # A tibble: 6 x 5
##    Code Revise  Exam Anxiety Gender
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; 
## 1     1      4    40    86.3 Male  
## 2     2     11    65    88.7 Female
## 3     3     27    80    70.2 Male  
## 4     4     53    80    61.3 Male  
## 5     5      4    40    89.5 Male  
## 6     6     22    70    60.5 Female</code></pre>
<p>Correlation anaylisis between anxiety, Exam and time for study (revise)</p>
<pre class="r"><code>cor(examData$Exam, examData$Anxiety, use = &quot;complete.obs&quot;,
    method = &#39;pearson&#39;)</code></pre>
<pre><code>## [1] -0.4409934</code></pre>
<pre class="r"><code>examData2 &lt;- examData[, c(&quot;Exam&quot;, &quot;Anxiety&quot;, &quot;Revise&quot;)]
head(examData2)</code></pre>
<pre><code>## # A tibble: 6 x 3
##    Exam Anxiety Revise
##   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1    40    86.3      4
## 2    65    88.7     11
## 3    80    70.2     27
## 4    80    61.3     53
## 5    40    89.5      4
## 6    70    60.5     22</code></pre>
<pre class="r"><code>cor(examData2)  # range from -1 to + 1</code></pre>
<pre><code>##               Exam    Anxiety     Revise
## Exam     1.0000000 -0.4409934  0.3967207
## Anxiety -0.4409934  1.0000000 -0.7092493
## Revise   0.3967207 -0.7092493  1.0000000</code></pre>
<pre class="r"><code>cor(examData[, c(&quot;Exam&quot;, &quot;Anxiety&quot;, &quot;Revise&quot;)])</code></pre>
<pre><code>##               Exam    Anxiety     Revise
## Exam     1.0000000 -0.4409934  0.3967207
## Anxiety -0.4409934  1.0000000 -0.7092493
## Revise   0.3967207 -0.7092493  1.0000000</code></pre>
<pre class="r"><code>cor(examData2)^2 * 100 # Ranges from 0 to 100  The proportion of the variance explained</code></pre>
<pre><code>##              Exam   Anxiety    Revise
## Exam    100.00000  19.44752  15.73873
## Anxiety  19.44752 100.00000  50.30345
## Revise   15.73873  50.30345 100.00000</code></pre>
<pre class="r"><code>#Coeficiente de determinación</code></pre>
<p>Using the corr.test function</p>
<pre class="r"><code>ggplot(examData2,aes(Revise, Anxiety))+
  geom_point()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>ggplot(examData,aes(Revise, Exam, colour=Gender))+
  geom_point()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>cor.test(examData$Anxiety, examData$Exam)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  examData$Anxiety and examData$Exam
## t = -4.938, df = 101, p-value = 3.128e-06
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.5846244 -0.2705591
## sample estimates:
##        cor 
## -0.4409934</code></pre>
<pre class="r"><code>cor.test(examData$Revise, examData$Exam)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  examData$Revise and examData$Exam
## t = 4.3434, df = 101, p-value = 3.343e-05
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2200938 0.5481602
## sample estimates:
##       cor 
## 0.3967207</code></pre>
<pre class="r"><code>cor.test(examData$Anxiety, examData$Revise)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  examData$Anxiety and examData$Revise
## t = -10.111, df = 101, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.7938168 -0.5977733
## sample estimates:
##        cor 
## -0.7092493</code></pre>
</div>
<div id="bivariate-plot-to-evaluate-the-distribution-of-both-variables" class="section level1">
<h1>Bivariate plot to evaluate the distribution of both variables</h1>
<p><a href="https://deanattali.com/2015/03/29/ggExtra-r-package/" class="uri">https://deanattali.com/2015/03/29/ggExtra-r-package/</a></p>
<p>Remember this code from chapter 5</p>
<pre class="r"><code>library(tidyverse)
a=rnorm(400, 0, 1)
b=rnorm(400, 0, 1.1)
#b=rbeta(400, 3, 1)
df=data.frame(a,b)
head(df)</code></pre>
<pre><code>##             a           b
## 1  0.09501955  2.43398523
## 2 -0.33626084 -0.62911250
## 3 -0.30911232  1.42872939
## 4 -0.54789689  0.21094219
## 5  0.24874075 -0.13639629
## 6  0.39099332 -0.07228516</code></pre>
<pre class="r"><code>out &lt;- stack(df)
out  </code></pre>
<pre><code>##           values ind
## 1    0.095019546   a
## 2   -0.336260839   a
## 3   -0.309112317   a
## 4   -0.547896890   a
## 5    0.248740750   a
## 6    0.390993323   a
## 7    0.267377086   a
## 8    0.697971485   a
## 9   -0.012590851   a
## 10   0.348542071   a
## 11   0.338682542   a
## 12   1.042989472   a
## 13  -0.987337786   a
## 14  -1.074560909   a
## 15  -1.130311777   a
## 16  -1.229993823   a
## 17   0.766227324   a
## 18  -1.338641854   a
## 19  -1.276029725   a
## 20  -2.545063608   a
## 21  -0.538583836   a
## 22   0.735127439   a
## 23  -0.633620297   a
## 24   1.729513088   a
## 25   1.460716295   a
## 26   0.386094436   a
## 27   0.519498033   a
## 28   0.119185812   a
## 29   0.035206952   a
## 30   1.447850099   a
## 31  -1.134300007   a
## 32  -0.348856498   a
## 33   1.692348842   a
## 34  -0.568176084   a
## 35  -0.286122695   a
## 36  -0.827834606   a
## 37  -0.366628554   a
## 38   0.398547226   a
## 39   0.599444948   a
## 40   0.139777175   a
## 41   0.886744286   a
## 42   0.501668202   a
## 43   1.240531343   a
## 44  -0.397930161   a
## 45  -0.404253839   a
## 46   1.425106317   a
## 47   0.438191495   a
## 48   1.003640544   a
## 49  -0.792903720   a
## 50   0.399213469   a
## 51   0.866116003   a
## 52  -1.464263195   a
## 53  -0.222202714   a
## 54   0.465392579   a
## 55  -1.707935746   a
## 56  -0.578848075   a
## 57   0.813961162   a
## 58   2.176306957   a
## 59  -0.103440335   a
## 60   0.600367177   a
## 61   0.619335411   a
## 62  -1.406232011   a
## 63   1.953313714   a
## 64   0.618507351   a
## 65  -0.930653505   a
## 66   1.666118789   a
## 67  -0.405651524   a
## 68   0.137068969   a
## 69  -1.479788074   a
## 70  -2.490579520   a
## 71  -0.112761347   a
## 72   1.082677478   a
## 73  -0.353145865   a
## 74  -0.752165268   a
## 75  -0.251290974   a
## 76  -0.304195729   a
## 77  -0.095892757   a
## 78   0.899564611   a
## 79  -1.420182326   a
## 80  -0.970365182   a
## 81   1.128755024   a
## 82  -0.262355054   a
## 83   0.879048892   a
## 84   0.723707220   a
## 85  -0.235773099   a
## 86   0.118559094   a
## 87  -1.737906507   a
## 88   0.187177086   a
## 89  -1.518114313   a
## 90   1.657453619   a
## 91   0.889377435   a
## 92  -0.146151070   a
## 93  -0.899268844   a
## 94   0.178467472   a
## 95  -0.686724675   a
## 96   1.644606716   a
## 97  -0.991744433   a
## 98  -0.255996886   a
## 99  -0.529674219   a
## 100  0.644406287   a
## 101 -0.700157150   a
## 102 -0.029330338   a
## 103  0.271614385   a
## 104 -0.509177834   a
## 105  0.231032979   a
## 106  0.077809698   a
## 107  0.221000817   a
## 108 -0.175394169   a
## 109 -0.224527505   a
## 110 -0.492037025   a
## 111  0.120461243   a
## 112 -0.760413017   a
## 113 -0.508165962   a
## 114 -1.231781334   a
## 115  0.955305030   a
## 116  0.033842897   a
## 117 -0.048968455   a
## 118  1.928070061   a
## 119 -0.475953870   a
## 120 -0.301128634   a
## 121 -0.389759100   a
## 122 -0.135817926   a
## 123  0.022149599   a
## 124 -0.327605830   a
## 125 -0.304455240   a
## 126 -0.561125365   a
## 127  1.125881680   a
## 128  0.379563526   a
## 129  1.065942947   a
## 130  0.182377919   a
## 131  1.912050833   a
## 132 -0.313286298   a
## 133  0.642972325   a
## 134  0.349848390   a
## 135 -1.631460889   a
## 136 -3.014662552   a
## 137  0.875478154   a
## 138  0.311437420   a
## 139  0.881899214   a
## 140  0.175480253   a
## 141  0.288681259   a
## 142  0.402678908   a
## 143 -0.850057134   a
## 144 -0.475041917   a
## 145  0.365431644   a
## 146  1.005508734   a
## 147 -0.508599481   a
## 148  0.543670139   a
## 149  0.349912433   a
## 150  0.340977480   a
## 151 -0.062084593   a
## 152  1.063002702   a
## 153 -2.067652995   a
## 154 -1.111233899   a
## 155 -0.171577609   a
## 156 -0.092851187   a
## 157 -0.970247618   a
## 158 -0.478368408   a
## 159  0.735606156   a
## 160 -0.256583477   a
## 161 -0.318467946   a
## 162 -0.239192659   a
## 163  0.799192350   a
## 164  1.282058392   a
## 165 -0.056825814   a
## 166 -0.153864529   a
## 167 -0.715374635   a
## 168 -0.321975047   a
## 169  0.617128746   a
## 170  1.658316734   a
## 171  1.150924018   a
## 172  2.010982730   a
## 173 -0.336576315   a
## 174 -0.497118435   a
## 175  0.388274956   a
## 176  0.333112841   a
## 177  0.821633942   a
## 178  0.356180080   a
## 179 -0.427023299   a
## 180  0.140720475   a
## 181  0.544556070   a
## 182 -1.007365561   a
## 183  0.308042275   a
## 184  1.098902351   a
## 185  1.612122347   a
## 186 -0.307634207   a
## 187 -0.700833019   a
## 188 -0.944922499   a
## 189 -0.439029965   a
## 190 -0.087843363   a
## 191  0.315312255   a
## 192  0.386974000   a
## 193 -0.464674925   a
## 194  0.656229782   a
## 195  1.244579628   a
## 196  0.749077375   a
## 197 -0.494110412   a
## 198 -1.089001245   a
## 199  0.156844729   a
## 200 -0.147087702   a
## 201 -0.076019895   a
## 202 -0.452661207   a
## 203  2.015113388   a
## 204 -0.472001663   a
## 205 -2.223596442   a
## 206  0.385810835   a
## 207  1.413552722   a
## 208 -0.412458596   a
## 209  0.228741893   a
## 210  0.589770720   a
## 211  2.384666495   a
## 212  1.010258645   a
## 213 -0.630088830   a
## 214 -0.293371962   a
## 215  1.147000900   a
## 216  0.994533359   a
## 217  0.181378465   a
## 218 -1.162776104   a
## 219  1.801218786   a
## 220 -0.116346932   a
## 221  0.083464927   a
## 222  0.921614828   a
## 223  0.370724107   a
## 224  1.341434479   a
## 225 -0.345076165   a
## 226 -0.978703660   a
## 227 -0.877011316   a
## 228 -0.313292965   a
## 229  1.777755203   a
## 230 -0.227842598   a
## 231  1.635972465   a
## 232  1.306166049   a
## 233 -0.114676419   a
## 234 -1.106658661   a
## 235 -1.208587017   a
## 236  0.550196484   a
## 237 -1.274340490   a
## 238  0.321600157   a
## 239 -0.516689073   a
## 240  1.177197699   a
## 241  1.236417545   a
## 242  0.241014039   a
## 243 -0.694419152   a
## 244 -1.113318164   a
## 245 -0.117392700   a
## 246  0.877320335   a
## 247  0.491599219   a
## 248  1.057099326   a
## 249 -0.391409935   a
## 250  0.282450717   a
## 251  0.205649867   a
## 252 -0.135883493   a
## 253 -1.217525225   a
## 254 -0.857933122   a
## 255  0.188954209   a
## 256  0.830131343   a
## 257 -0.471229260   a
## 258  0.380469787   a
## 259 -1.717115220   a
## 260  0.705482524   a
## 261 -1.319539833   a
## 262 -0.880535110   a
## 263  0.229550089   a
## 264 -0.384451581   a
## 265  0.008990281   a
## 266 -0.305585563   a
## 267 -0.670663607   a
## 268 -0.283966234   a
## 269 -1.636380694   a
## 270  0.648570849   a
## 271 -0.580629613   a
## 272 -0.938784903   a
## 273  0.186166424   a
## 274  0.585431618   a
## 275 -0.871913395   a
## 276  0.109755079   a
## 277 -0.303794030   a
## 278  1.841205616   a
## 279  1.704703085   a
## 280  1.416811635   a
## 281  0.992759665   a
## 282 -0.749076769   a
## 283 -0.015083856   a
## 284 -2.552336549   a
## 285  1.263548488   a
## 286  1.549827171   a
## 287  1.449549382   a
## 288 -0.230330724   a
## 289  0.093583384   a
## 290 -1.282496255   a
## 291 -0.011527824   a
## 292 -1.019401158   a
## 293 -0.757205176   a
## 294 -2.226270497   a
## 295  0.301196579   a
## 296 -0.204463427   a
## 297  1.982094529   a
## 298 -0.825198143   a
## 299 -0.249043339   a
## 300  0.476565460   a
## 301  0.095994123   a
## 302  0.956432291   a
## 303  0.535867781   a
## 304 -0.336369185   a
## 305  0.261676670   a
## 306 -2.004907019   a
## 307 -0.297763957   a
## 308 -1.054635953   a
## 309 -0.314107579   a
## 310  0.433820531   a
## 311 -1.212657903   a
## 312  1.049810717   a
## 313  0.913500487   a
## 314 -0.344990736   a
## 315  0.333660186   a
## 316 -0.787760351   a
## 317  2.044109071   a
## 318 -0.761599419   a
## 319 -0.533179215   a
## 320  0.831573472   a
## 321 -0.864938493   a
## 322  1.075004015   a
## 323  0.029752962   a
## 324 -0.687567765   a
## 325  1.367999930   a
## 326  0.900643268   a
## 327  0.515071701   a
## 328 -1.149082648   a
## 329 -0.220175075   a
## 330  0.686764725   a
## 331 -1.068540073   a
## 332 -0.827722739   a
## 333 -0.187477793   a
## 334 -0.400961990   a
## 335 -0.874801935   a
## 336  0.077150299   a
## 337 -0.884965491   a
## 338 -0.350026654   a
## 339 -0.176025169   a
## 340  0.803140400   a
## 341 -0.463239307   a
## 342  2.610376393   a
## 343 -1.490143102   a
## 344 -0.468065142   a
## 345 -0.481693004   a
## 346 -1.875424939   a
## 347 -0.558035962   a
## 348 -0.281213123   a
## 349 -0.580028897   a
## 350 -0.735716112   a
## 351 -0.334693623   a
## 352 -0.709091111   a
## 353 -1.050062145   a
## 354  1.706358339   a
## 355 -0.480076658   a
## 356 -0.175321488   a
## 357 -1.693674623   a
## 358  0.157843811   a
## 359  0.083966063   a
## 360  1.221346140   a
## 361 -0.252452523   a
## 362 -0.906117189   a
## 363  0.900305865   a
## 364 -0.573142162   a
## 365 -1.130809315   a
## 366  1.704283698   a
## 367  1.598887369   a
## 368  0.218833864   a
## 369 -0.594058995   a
## 370  0.424464495   a
## 371  0.139658315   a
## 372  1.449734891   a
## 373  1.355244547   a
## 374 -0.198760354   a
## 375 -0.788497404   a
## 376 -0.944611577   a
## 377 -0.811477262   a
## 378  0.340099450   a
## 379  1.755352640   a
## 380  0.647651622   a
## 381  0.877342055   a
## 382 -0.408529800   a
## 383  0.413548578   a
## 384 -1.243851834   a
## 385  0.538499209   a
## 386 -0.181299737   a
## 387 -0.624658194   a
## 388 -1.116781988   a
## 389  0.435474141   a
## 390  0.513147055   a
## 391  1.286258538   a
## 392  0.361595791   a
## 393  0.445512603   a
## 394 -1.953061459   a
## 395  1.024591772   a
## 396  0.306530331   a
## 397  0.591567382   a
## 398  1.453546842   a
## 399  0.338172987   a
## 400 -0.312408750   a
## 401  2.433985228   b
## 402 -0.629112501   b
## 403  1.428729386   b
## 404  0.210942188   b
## 405 -0.136396293   b
## 406 -0.072285158   b
## 407  1.490374564   b
## 408  1.371316742   b
## 409 -1.743503858   b
## 410  1.953222263   b
## 411 -0.781902745   b
## 412 -1.501360865   b
## 413 -0.385708477   b
## 414  0.064889033   b
## 415  0.689166453   b
## 416 -1.268778152   b
## 417  0.515559440   b
## 418 -0.779274959   b
## 419  1.703308746   b
## 420  0.669190284   b
## 421  1.826894614   b
## 422  0.576691536   b
## 423 -1.829062394   b
## 424  0.882318452   b
## 425  0.992389581   b
## 426  0.739248026   b
## 427  1.502229470   b
## 428 -1.283006163   b
## 429 -1.016951111   b
## 430 -1.385847552   b
## 431 -0.572393430   b
## 432  0.053825196   b
## 433  0.683427141   b
## 434  0.498725807   b
## 435 -1.163058383   b
## 436 -0.358975779   b
## 437  2.022644696   b
## 438 -1.368542991   b
## 439 -1.190290327   b
## 440  0.353581643   b
## 441  1.602037802   b
## 442 -1.371366747   b
## 443  0.710318286   b
## 444  0.694101026   b
## 445 -1.906213444   b
## 446 -0.503566461   b
## 447  0.196585467   b
## 448 -0.584779175   b
## 449 -0.504130514   b
## 450 -1.115477418   b
## 451  0.149305647   b
## 452 -1.804944371   b
## 453 -1.157222678   b
## 454  2.302066448   b
## 455 -1.247779487   b
## 456 -0.143429574   b
## 457  1.980226003   b
## 458  0.734158859   b
## 459  0.443983542   b
## 460  0.140955816   b
## 461 -0.164103920   b
## 462 -1.599655015   b
## 463 -1.969362230   b
## 464  0.213138347   b
## 465  0.992609404   b
## 466  2.443076920   b
## 467  0.327268570   b
## 468 -1.370494629   b
## 469 -0.147654662   b
## 470 -1.856719058   b
## 471 -1.922750045   b
## 472 -1.143163638   b
## 473 -2.073879168   b
## 474 -0.019784682   b
## 475 -0.866668571   b
## 476 -1.050141033   b
## 477 -0.713348597   b
## 478 -0.650524685   b
## 479  1.107221050   b
## 480  1.021743256   b
## 481 -0.623268499   b
## 482  0.080973174   b
## 483 -0.394872901   b
## 484  0.712209161   b
## 485  3.357027342   b
## 486 -0.317996010   b
## 487  0.286374680   b
## 488 -0.731175878   b
## 489  0.341390688   b
## 490 -2.204059350   b
## 491 -0.782043851   b
## 492 -0.571423099   b
## 493 -0.301122655   b
## 494  0.408292063   b
## 495  1.748300592   b
## 496  0.055392263   b
## 497  0.875538277   b
## 498  0.462839850   b
## 499 -1.933432306   b
## 500 -1.092080411   b
## 501  1.057021831   b
## 502  0.584764459   b
## 503  1.344839638   b
## 504  1.246203220   b
## 505 -0.016444606   b
## 506  1.923181487   b
## 507 -1.796794080   b
## 508  0.924120648   b
## 509  2.004178364   b
## 510  0.587107018   b
## 511  0.778778739   b
## 512  0.911750813   b
## 513 -2.132293164   b
## 514  1.755079861   b
## 515 -0.053346230   b
## 516 -0.743669036   b
## 517  0.185406647   b
## 518  1.530532268   b
## 519  1.116995020   b
## 520 -0.087331441   b
## 521 -0.223385509   b
## 522  1.048993576   b
## 523  0.619111082   b
## 524  0.687610423   b
## 525 -1.982823358   b
## 526 -1.009872129   b
## 527  0.879677693   b
## 528  0.285324661   b
## 529 -2.573245141   b
## 530 -1.547707142   b
## 531  0.284620500   b
## 532  0.239781588   b
## 533  1.150008619   b
## 534 -2.110201995   b
## 535  0.841533467   b
## 536  0.039608553   b
## 537  0.524214065   b
## 538 -0.796306265   b
## 539 -0.168352084   b
## 540  2.423701552   b
## 541  0.245407912   b
## 542  1.100849118   b
## 543 -3.132753671   b
## 544  1.963852776   b
## 545  1.903435461   b
## 546 -0.316888122   b
## 547 -0.090570485   b
## 548 -0.071893784   b
## 549 -1.991211060   b
## 550  0.198545866   b
## 551 -0.428695873   b
## 552  0.584824009   b
## 553 -0.774103244   b
## 554  0.146599608   b
## 555 -0.807537030   b
## 556 -0.652766806   b
## 557 -0.021306042   b
## 558  0.448321606   b
## 559 -0.508102573   b
## 560 -1.307658957   b
## 561  0.128387344   b
## 562  0.086749149   b
## 563 -1.563537938   b
## 564  0.384279264   b
## 565  1.591688280   b
## 566 -1.122483567   b
## 567  0.180843555   b
## 568  0.755082695   b
## 569 -1.917534055   b
## 570  0.074544860   b
## 571  0.078781529   b
## 572 -0.708494559   b
## 573  0.772744745   b
## 574 -0.865550667   b
## 575  3.482447380   b
## 576  0.792736915   b
## 577  0.802734801   b
## 578  0.772337926   b
## 579 -0.039795408   b
## 580  2.559432813   b
## 581  1.782066803   b
## 582  1.559523178   b
## 583 -0.358729480   b
## 584 -2.921126085   b
## 585 -1.166186231   b
## 586  0.005703285   b
## 587  0.072882713   b
## 588 -2.039919701   b
## 589  0.290615132   b
## 590 -0.168985321   b
## 591  1.408377890   b
## 592 -0.160635982   b
## 593 -1.350195812   b
## 594  1.296740708   b
## 595  0.118378537   b
## 596  0.443279924   b
## 597 -0.615585913   b
## 598  0.138362080   b
## 599  0.869021163   b
## 600  1.409669406   b
## 601 -0.205826035   b
## 602 -1.425470974   b
## 603 -2.233269839   b
## 604 -0.142061772   b
## 605  0.736017237   b
## 606 -2.661417215   b
## 607  0.397323790   b
## 608 -0.090762057   b
## 609 -1.330211893   b
## 610 -0.487450412   b
## 611 -1.589361651   b
## 612 -1.199958151   b
## 613 -2.021204508   b
## 614 -0.917001928   b
## 615  0.533417202   b
## 616  1.407628402   b
## 617 -0.951254344   b
## 618 -2.333436881   b
## 619 -0.214277323   b
## 620  0.052805215   b
## 621  2.111540632   b
## 622  0.497135663   b
## 623 -0.491582368   b
## 624  0.875410612   b
## 625  0.638976444   b
## 626  1.034561485   b
## 627 -1.213161437   b
## 628 -1.169269505   b
## 629 -1.655217965   b
## 630 -0.259639011   b
## 631 -1.072697910   b
## 632 -1.850410397   b
## 633  0.568644041   b
## 634  0.562404372   b
## 635 -0.134542974   b
## 636  0.713672787   b
## 637  0.891608522   b
## 638 -0.888105563   b
## 639  0.764524031   b
## 640  0.890983115   b
## 641 -0.267756609   b
## 642 -1.439169496   b
## 643  1.018848129   b
## 644  2.498403435   b
## 645  0.501857662   b
## 646 -1.363633670   b
## 647 -1.897134403   b
## 648 -1.540243707   b
## 649 -0.776878788   b
## 650  0.693631768   b
## 651 -0.644145151   b
## 652  1.635320657   b
## 653  1.921175833   b
## 654 -1.243105183   b
## 655 -0.835911531   b
## 656 -1.443379070   b
## 657 -0.230911875   b
## 658 -0.475856443   b
## 659  0.585435789   b
## 660  0.992199348   b
## 661 -1.029096913   b
## 662  0.608214799   b
## 663  0.368513044   b
## 664 -0.022999491   b
## 665 -2.024156631   b
## 666  0.266126529   b
## 667 -0.419566774   b
## 668  1.718578366   b
## 669 -1.188860591   b
## 670  1.511432641   b
## 671  0.351458322   b
## 672  1.468257802   b
## 673  2.129521661   b
## 674 -0.093910165   b
## 675  0.451279907   b
## 676 -1.028333394   b
## 677  0.527399651   b
## 678 -1.595588165   b
## 679 -0.744917917   b
## 680  0.896742301   b
## 681 -0.397344536   b
## 682 -1.259561412   b
## 683  0.741402284   b
## 684 -0.205657263   b
## 685 -0.643768988   b
## 686  0.196831707   b
## 687 -1.015044069   b
## 688 -1.254986376   b
## 689  0.358754674   b
## 690 -2.261301857   b
## 691 -0.537731742   b
## 692 -0.186686601   b
## 693 -0.420248748   b
## 694  2.046822067   b
## 695  0.171432323   b
## 696  1.598738173   b
## 697 -0.302808256   b
## 698  0.207616850   b
## 699 -0.528549820   b
## 700 -0.701749338   b
## 701 -0.948919932   b
## 702  0.468176226   b
## 703 -0.434605194   b
## 704  1.252031139   b
## 705  1.006236563   b
## 706  0.296987857   b
## 707 -0.861499199   b
## 708 -0.411313488   b
## 709 -0.982448625   b
## 710 -2.450895331   b
## 711  0.667954352   b
## 712 -0.903916124   b
## 713  0.705819424   b
## 714  1.002002458   b
## 715 -1.357859263   b
## 716 -0.979580951   b
## 717  0.317690503   b
## 718  0.275163495   b
## 719  0.099922691   b
## 720  0.221703773   b
## 721  0.463715063   b
## 722 -0.134793123   b
## 723 -0.746227507   b
## 724  0.399814476   b
## 725 -0.070971267   b
## 726  0.065092834   b
## 727  1.939054144   b
## 728  0.474192724   b
## 729  0.893385966   b
## 730 -1.787975884   b
## 731 -2.599849697   b
## 732  0.014556104   b
## 733 -0.765256824   b
## 734  2.070075572   b
## 735 -1.445435416   b
## 736  0.226213445   b
## 737  1.702917950   b
## 738 -1.355173448   b
## 739  0.777227705   b
## 740 -0.481568793   b
## 741  0.413620535   b
## 742 -0.823286875   b
## 743  0.121731478   b
## 744 -0.939881804   b
## 745 -1.407984781   b
## 746 -2.609333526   b
## 747  0.524891819   b
## 748 -0.761345088   b
## 749  0.151341480   b
## 750 -0.337815993   b
## 751 -1.383091519   b
## 752 -1.510149094   b
## 753 -1.348666574   b
## 754 -0.315753005   b
## 755  0.089224686   b
## 756  0.901414272   b
## 757  0.088157985   b
## 758 -0.040387669   b
## 759  0.993850369   b
## 760  0.198335009   b
## 761 -0.048708558   b
## 762  1.027767859   b
## 763  0.516185648   b
## 764 -0.165324349   b
## 765  0.848978914   b
## 766 -2.197552695   b
## 767 -0.048565459   b
## 768 -2.770123914   b
## 769  0.879058077   b
## 770 -0.574299937   b
## 771  0.915569930   b
## 772  0.173879358   b
## 773  0.132053232   b
## 774  1.732887999   b
## 775  0.265818584   b
## 776  0.739563643   b
## 777 -0.929980449   b
## 778 -0.401128724   b
## 779 -1.628640492   b
## 780  2.393567042   b
## 781  1.474903415   b
## 782 -0.123893061   b
## 783 -0.026276471   b
## 784  0.226802496   b
## 785 -0.091214500   b
## 786 -2.741775968   b
## 787  1.481950855   b
## 788  0.226521159   b
## 789  0.742593318   b
## 790 -0.441202957   b
## 791 -0.378805321   b
## 792 -0.987304205   b
## 793 -1.221116056   b
## 794  3.353315505   b
## 795 -0.001413391   b
## 796  1.381018582   b
## 797 -1.428899263   b
## 798 -0.290472933   b
## 799 -0.008596467   b
## 800 -0.641748015   b</code></pre>
<pre class="r"><code>ggplot(out, aes(values, colour=ind, fill=ind))+
  geom_histogram()+
  facet_wrap(~ind)</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>library(car)

leveneTest(out$values, out$ind)</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value    Pr(&gt;F)    
## group   1  16.456 5.468e-05 ***
##       798                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#install.packages(&quot;ggExtra&quot;, dependencies = TRUE)
library(ggExtra)

p &lt;- ggplot(df, aes(a, b)) + geom_point() + 
  theme_classic()
# add marginal histograms
ggExtra::ggMarginal(p, type = &quot;histogram&quot;)</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The biggest liar data</p>
<pre class="r"><code>library(ggplot2)
library(readr)
The_Biggest_Liar &lt;- read_csv(&quot;~/Google Drive/Biometry/Biometria 2015/Biometria_2015_RStudio/Data files/The Biggest Liar.csv&quot;)

liarData=The_Biggest_Liar 
liarData</code></pre>
<pre><code>## # A tibble: 68 x 3
##    Creativity Position Novice
##         &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1         53        1      0
##  2         36        3      1
##  3         31        4      0
##  4         43        2      0
##  5         30        4      1
##  6         41        1      0
##  7         32        4      0
##  8         54        1      1
##  9         47        2      1
## 10         50        2      0
## # … with 58 more rows</code></pre>
<pre class="r"><code>length(liarData$Creativity)</code></pre>
<pre><code>## [1] 68</code></pre>
<pre class="r"><code>summary(liarData)</code></pre>
<pre><code>##    Creativity       Position         Novice      
##  Min.   :21.00   Min.   :1.000   Min.   :0.0000  
##  1st Qu.:35.00   1st Qu.:1.000   1st Qu.:0.0000  
##  Median :39.00   Median :2.000   Median :1.0000  
##  Mean   :39.99   Mean   :2.221   Mean   :0.5147  
##  3rd Qu.:45.25   3rd Qu.:3.000   3rd Qu.:1.0000  
##  Max.   :56.00   Max.   :6.000   Max.   :1.0000</code></pre>
<p>Como cambiar el nombre de la variables</p>
<pre class="r"><code>names(liarData)</code></pre>
<pre><code>## [1] &quot;Creativity&quot; &quot;Position&quot;   &quot;Novice&quot;</code></pre>
<pre class="r"><code>names(liarData)[1]=paste(&quot;Creatividad&quot;)  # se cambia el nombre de la columna
names(liarData)</code></pre>
<pre><code>## [1] &quot;Creatividad&quot; &quot;Position&quot;    &quot;Novice&quot;</code></pre>
<pre class="r"><code>names(liarData)[2]=paste(&quot;Posición&quot;)
names(liarData)[3]=paste(&quot;Principiante&quot;)
head(liarData)</code></pre>
<pre><code>## # A tibble: 6 x 3
##   Creatividad Posición Principiante
##         &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;
## 1          53        1            0
## 2          36        3            1
## 3          31        4            0
## 4          43        2            0
## 5          30        4            1
## 6          41        1            0</code></pre>
<p>Evaluar si las variables tienen distribución normal</p>
<pre class="r"><code>p &lt;- ggplot(liarData, aes(Creatividad, Posición)) + 
  geom_point() + 
  theme_classic()
p
# add marginal histograms
ggExtra::ggMarginal(p, type = &quot;histogram&quot;)</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>ggplot(liarData, aes(Posición))+ 
  geom_histogram(fill=&quot;blue&quot;, colour=&quot;white&quot;)</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>ggplot(liarData, aes(Creatividad))+
  geom_histogram()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<p>Spearman Correlations</p>
<pre class="r"><code>library(knitr)
library(png)

img4_path&lt;-&quot;Graficos/Stanton.png&quot;
include_graphics(img4_path)</code></pre>
<p><img src="Graficos/Stanton.png" width="500px" /></p>
<pre class="r"><code>#-------Spearman correlation-----Use when data are not normal, 
# such as ordinal data

cor(liarData$Posición, liarData$Creatividad, method = &quot;spearman&quot;)</code></pre>
<pre><code>## [1] -0.3732184</code></pre>
<pre class="r"><code>cor.test(liarData$Posición, liarData$Creatividad, method = &quot;spearman&quot;)</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  liarData$Posición and liarData$Creatividad
## S = 71948, p-value = 0.00172
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## -0.3732184</code></pre>
<pre class="r"><code>cor.test(liarData$Posición, liarData$Creatividad, alternative = &quot;less&quot;, method = &quot;kendall&quot;)</code></pre>
<pre><code>## 
##  Kendall&#39;s rank correlation tau
## 
## data:  liarData$Posición and liarData$Creatividad
## z = -3.2252, p-value = 0.0006294
## alternative hypothesis: true tau is less than 0
## sample estimates:
##        tau 
## -0.3002413</code></pre>
<pre class="r"><code>ggplot(liarData,aes(Posición, Creatividad))+
  geom_point()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/Spearman-1.png" width="672" /></p>
<pre class="r"><code>ggplot(liarData, aes(Posición, Creatividad))+
  geom_point()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Another alternative</p>
<pre class="r"><code>library(Hmisc)  # for the function rcorr
liarMatrix&lt;-as.matrix(liarData[, c(&quot;Posición&quot;, &quot;Creatividad&quot;, &quot;Principiante&quot;)])
liarMatrix</code></pre>
<pre><code>##       Posición Creatividad Principiante
##  [1,]        1          53            0
##  [2,]        3          36            1
##  [3,]        4          31            0
##  [4,]        2          43            0
##  [5,]        4          30            1
##  [6,]        1          41            0
##  [7,]        4          32            0
##  [8,]        1          54            1
##  [9,]        2          47            1
## [10,]        2          50            0
## [11,]        1          56            0
## [12,]        1          50            0
## [13,]        1          34            1
## [14,]        4          41            0
## [15,]        5          52            0
## [16,]        1          38            0
## [17,]        2          35            1
## [18,]        3          35            1
## [19,]        1          48            0
## [20,]        1          38            1
## [21,]        2          43            1
## [22,]        3          38            1
## [23,]        1          39            1
## [24,]        1          51            0
## [25,]        3          26            0
## [26,]        4          31            1
## [27,]        1          45            0
## [28,]        3          31            0
## [29,]        2          34            1
## [30,]        5          35            1
## [31,]        2          39            1
## [32,]        2          50            1
## [33,]        1          53            1
## [34,]        2          38            0
## [35,]        3          37            0
## [36,]        2          34            1
## [37,]        1          30            0
## [38,]        6          46            0
## [39,]        2          36            1
## [40,]        1          26            1
## [41,]        1          41            1
## [42,]        6          50            1
## [43,]        1          43            0
## [44,]        2          54            0
## [45,]        1          39            1
## [46,]        2          51            0
## [47,]        1          47            0
## [48,]        3          38            1
## [49,]        1          32            0
## [50,]        4          28            1
## [51,]        1          39            0
## [52,]        1          42            1
## [53,]        2          44            0
## [54,]        5          21            1
## [55,]        1          43            1
## [56,]        3          39            1
## [57,]        1          42            1
## [58,]        2          35            0
## [59,]        1          52            0
## [60,]        1          39            0
## [61,]        1          45            0
## [62,]        4          25            1
## [63,]        1          41            1
## [64,]        3          35            1
## [65,]        3          27            0
## [66,]        4          44            0
## [67,]        3          37            1
## [68,]        1          40            1</code></pre>
<pre class="r"><code>rcorr(liarMatrix, type=c(&quot;spearman&quot;)) # si no pone nada asume distribución normal y usa Pearson</code></pre>
<pre><code>##              Posición Creatividad Principiante
## Posición         1.00       -0.37         0.11
## Creatividad     -0.37        1.00        -0.27
## Principiante     0.11       -0.27         1.00
## 
## n= 68 
## 
## 
## P
##              Posición Creatividad Principiante
## Posición              0.0017      0.3777      
## Creatividad  0.0017               0.0281      
## Principiante 0.3777   0.0281</code></pre>
<pre class="r"><code>#--------Kendall&#39;s Tau----------Use with small sample size with tied ranks
# use &quot;less&quot; or &quot;greater&quot;, depending if you 
# predict that the correlation will be less or greater than zero

#cor(liarData$Posición, liarData$Creatividad, method = &quot;kendall&quot;)
#cor.test(liarData$Posición, liarData$Creatividad, alternative = &quot;less&quot;, method = &quot;kendall&quot;)</code></pre>
<pre class="r"><code>ggplot(examData, aes(Exam))+
         geom_histogram()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/hist%20anxiety-1.png" width="672" /></p>
<pre class="r"><code>ggplot(examData, aes(Anxiety))+
         geom_histogram()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/hist%20anxiety-2.png" width="672" /></p>
<pre class="r"><code>cor.test(examData$Anxiety, examData$Exam, method = &quot;kendall&quot;)</code></pre>
<pre><code>## 
##  Kendall&#39;s rank correlation tau
## 
## data:  examData$Anxiety and examData$Exam
## z = -4.113, p-value = 3.906e-05
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##        tau 
## -0.2847919</code></pre>
<pre class="r"><code>ggplot(examData, aes(Anxiety, Exam))+
  geom_point()</code></pre>
<p><img src="T13_Correlacion_files/figure-html/kendall%20exam%20anxiety-1.png" width="672" /></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
