---
title: "T9b"
output: 
  html_document:
    css: tutorial.css
    fig_caption: yes
    highlight: pygments
#    theme: simplex
    toc: yes
    toc_float: yes
    code_folding: hide
   
---



```{r setup, include=FALSE}
library(knitr)
#knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
library(knitr)
#library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
knitr::opts_chunk$set(error = FALSE)
#getwd()
```

```{r, echo=FALSE}
library(tidyverse)

rlt_theme <- theme(axis.title.y = element_line(linewidth=15, colour="grey20"),
        axis.text.x = element_line(linewidth=10,  colour="grey20"),
        axis.text.y = element_line(linewidth=15, colour="grey20"),  
        axis.title.x = element_line(linewidth=15), colour="grey20")+
  theme(
  # Remove panel border
  panel.border = element_blank(),  
  # Remove panel grid lines
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Remove panel background
  panel.background = element_blank(),
  # add thicker border lines
    axis.line.x = element_line(colour = "black", element_line(linewidth=1)),
    axis.line.y = element_line(colour = "black", element_line(linewidth=1))
  )

# The palette with grey:
cbPalette1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbPalette2 <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# To use for fills, add
#  scale_fill_manual(values=cbPalette)

# To use for line and point colors, add
  #scale_colour_manual(values=cbPalette)

```


```{r, eval=TRUE, echo=FALSE}
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

#`r colorize("some words in red", "red")`


```

