---
title: "BVec"
author: "Raymond L. Tremblay"
date: "10/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}

trimpb<-function(x,y=NULL,tr=.2,alpha=.05,nboot=2000,WIN=FALSE,win=.1,
                plotit=FALSE,pop=1,null.value=0,pr=TRUE,xlab="X",fr=NA,SEED=TRUE){
 #
 #   Compute a 1-alpha confidence interval for
 #   a trimmed mean.
 #
 #   The default number of bootstrap samples is nboot=2000
 #
 #   win is the amount of Winsorizing before bootstrapping
 #   when WIN=T.
 #
 #   Missing values are automatically removed.
 #
 #  nv is null value. That test hypothesis trimmed mean equals nv
 #
 #  plotit=TRUE gives a plot of the bootstrap values
 #  pop=1 results in the expected frequency curve.
 #  pop=2 kernel density estimate
 #  pop=3 boxplot
 #  pop=4 stem-and-leaf
 #  pop=5 histogram
 #  pop=6 adaptive kernel density estimate.
 #
 #  fr controls the amount of smoothing when plotting the bootstrap values
 #  via the function rdplot. fr=NA means the function will use fr=.8
 #  (When plotting bivariate data, rdplot uses fr=.6 by default.)
 #
 #  If y is not null, the function uses x-y; so can be used for two dependent variables.
 #
 if(pr){
   print("The p-value returned by this function is based on the")
   print("null value specified by the argument null.value, which defaults to 0")
 }
 if(!is.null(y))x=x-y
 x<-x[!is.na(x)]
 if(WIN){
   if(win > tr)stop("The amount of Winsorizing must be <= to the amount of trimming")
   x<-winval(x,win)
 }
 crit<-alpha/2
 icl<-round(crit*nboot)+1
 icu<-nboot-icl
 bvec<-NA
 if(SEED)set.seed(2) # set seed of random number generator so that
 #             results can be duplicated.
 data<-matrix(sample(x,size=length(x)*nboot,replace=TRUE),nrow=nboot)
 #datatr<-apply(data,tr)
 bvec<-apply(data,1,mean,tr) # Bootstrapped trimmed means
 bvec<-sort(bvec)
 #p.value<-sum(bvec<null.value)/nboot
 p.value<-mean(bvec<null.value)+.5*mean(bvec==null.value)
 p.value<-2*min(p.value,1-p.value)
 ci<-NA
 ci[1]<-bvec[icl]
 ci[2]<-bvec[icu]
 if(plotit){
   if(pop==1)rdplot(as.vector(bvec),fr=fr,xlab=xlab)
   if(pop==2)kdplot(as.vector(bvec),rval=rval)
   if(pop==3)boxplot(as.vector(bvec))
   if(pop==4)stem(as.vector(bvec))
   if(pop==5)hist(as.vector(bvec))
   if(pop==6)akerd(as.vector(bvec),xlab=xlab)
 }
 list(estimate=mean(x,tr=tr),ci=ci,bvec=bvec,data=data,p.value=p.value)
}
```

```{r}
df=c(1:50)
```


```{r}
trimpb(df, nboot=5)
```

```{r}
winval<-function(x,tr=.2){
#
#  Winsorize the data in the vector x.
#  tr is the amount of Winsorization which defaults to .2.
#
#  This function is used by several other functions that come with this book.
#
y<-sort(x)
n<-length(x)
ibot<-floor(tr*n)+1
itop<-length(x)-ibot+1
xbot<-y[ibot]
xtop<-y[itop]
winval<-ifelse(x<=xbot,xbot,x)
winval<-ifelse(winval>=xtop,xtop,winval)
list(winval, y, xbot, xtop)
}
```

```{r}
df2=c(1:100)
winval(df2, tr = .05)
```

